import React from 'react';
import NavigationBar from '../components/navigationbar/navigationbar';
import { CartProvider } from '../contexts/cartcontext/cartcontext';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Video Game Store Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <NavigationBar /> 
          {children}
        </CartProvider>
      </body>
    </html>
  );
}